title: Quod Avis
description: Find out what bird you've taken a picture of!
about:


  This is a classifier of birds using deep learning built using FastAI on top of Pytorch.


  The project was build by Kaushik Muralidharan.


  More info and the source code can he found below.

  - [Web App](https://quodavis.herokuapp.com)

  - [Blog of Creators of Original App (they made a food classifier)](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)


code: https://github.com/kausmik/web-deep-learning-classifier

sampleImages:
  - name: Mute Swan
    url: https://en.wikipedia.org/wiki/Swan#/media/File:Cygnus_olor_2_(Marek_Szczepanek).jpg
  - name: House Sparrow
    url: https://en.wikipedia.org/wiki/House_sparrow#/media/File:House_Sparrow,_England_-_May_09.jpg
  - name: Baya Weaver
    url: https://en.wikipedia.org/wiki/File:Baya_Weaver_(Ploceus_philippinus)-_Immature_in_Kolkata_I_IMG_8143.jpg
  - name: Chaffinch
    url: https://en.wikipedia.org/wiki/File:Fringilla_coelebs_chaffinch_male_edit2.jpg
  - name: Orange-Bellied Leafbird
    url: https://en.wikipedia.org/wiki/File:Orange_bellied_leafbird.jpg
